export const doctorConsts = {
    GET_DOCTORS: "GET_DOCTORS",
    GET_SINGLE_DOCTOR: "GET_SINGLE_DOCTOR",
    CREATE_DOCTOR: "CREATE_DOCTOR",
    EDIT_DOCTOR: "EDIT_DOCTOR",
    DELETE_DOCTOR: "DELETE_DOCTOR"
}

export const hospitalConsts = {
    GET_HOSPITALS: "GET_HOSPITALS",
    GET_SINGLE_HOSPITAL: "GET_SINGLE_HOSPITAL",
    CREATE_HOSPITAL: "CREATE_HOSPITAL",
    EDIT_HOSPITAL: "EDIT_HOSPITAL",
    DELETE_HOSPITAL: "DELETE_HOSPITAL"
}

export const reviewsConsts = {
    GET_REVIRES: "GET_REVIEWS"
}

export const roomsConsts = {
    GET_ROOMS: "GET_ROOMS",
    GET_SINGLE_ROOM: "GET_SINGLE_ROOM",
    CREATE_ROOM: "CREATE_ROOM",
    EDIT_ROOM: "EDIT_ROOM",
    DELETE_ROOM: "DELETE_ROOM"
}

export const ownersConst = {
    LOGIN_OWNERS: "LOGIN_OWNERS",
    SIGNUP_OWNERS: "SIGNUP_OWNERS",
    LOGOUT_OWNERS: "LOGOUT_OWNERS"
}

export const ratingsConst = {
    GET_SINGLE_HOPITAL_RATINGS: "GET_SINGLE_HOPITAL_RATINGS"
}